# Definition for the iprejecter instance type
# Specifies which the script to run to track ip connections on an instance

heat_template_version: 2015-04-30

parameters:
  PndaMirror:
    description: URL of a mirror for operating system package download
    type: string
    default: ''
  NtpServers:
    description: NTP servers
    type: string
    default: ''
  keystone_auth_url:
    type: string

resources:
  iprejecter_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config: 
        str_replace:
          template: { get_file: scripts/iprejecter.sh }
          params: 
            $pnda_mirror$: { get_param: PndaMirror }
            $ntp_servers$: { get_param: NtpServers }
            $keystone_auth_url$: { get_param: keystone_auth_url }
outputs:
  OS::stack_id:
    value: { get_resource: iprejecter_config }
