# Definition for the iptracker instance type
# Specifies which the script to run to track ip connections on an instance

heat_template_version: 2015-04-30

resources:
  iptracker_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config: 
        { get_file: scripts/iptracker.sh }
outputs:
  OS::stack_id:
    value: { get_resource: iptracker_config }
