heat_template_version: 2014-10-16

parameters:
  SaltmasterFlavor:
    type: string
    description: Falvor for the salmaster nodes
    default: pnda-micro
  Manager1Flavor:
    type: string
    description: Falvor for the manager nodes
    default: pnda-micro
  EdgeFlavor:
    type: string
    description: Falvor for the edge node
    default: pnda-micro
  BastionFlavor:
    type: string
    description: Flavor for the bastion nodes
    default: pnda-micro
  KafkaFlavor:
    type: string
    description: Flavor for the kafka nodes
    default: pnda-micro
  DatanodeFlavor:
    type: string
    description: Flavor for the data nodes
    default: pnda-micro
  image_id:
    type: string
    description: default image for pnda servers
    default: ubuntu1404

  DataNodes:
    default: '1'
    description: Number of DATA nodes
    type: string



  DatanodeVolumeSize:
    default: 10
    type: number
  DatanodeMountpoint:
    default: /dev/vdc
    type: string

  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
  private_net:
    type: string
  private_subnet:
    type: string
  KeyName:
    description: Name of an existing KeyPair to enable SSH access to the instances
    type: string
  git_private_key_file:
    description: private key file for cloning from git
    type: string
  PndaFlavor:
    description: pnda flavor
    type: string
    default: standard
  git_private_key_file:
    description: private key file for cloning from git
    type: string
  SaltmasterIP:
    type: string
  PndaSecGroup:
    type: string
  private_key:
    type: string
  BastionKeyName:
    type: string
  deployment_name:
    type: string

resources:
  KafkaSecGroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for Kafka Nodes
      name:
        str_replace:
          template:
            cname-kafka
          params:
            cname: { get_param: deployment_name }
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443          
  DNSecGroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for Data Nodes
      name:
        str_replace:
          template:
            cname-dn
          params:
            cname: { get_param: deployment_name }
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
  
  bastion:
    type: OS::Pnda::bastion
    properties:
      Flavor: { get_param: BastionFlavor }
      Image: { get_param: image_id }
      KeyName: { get_param: BastionKeyName }
      name:
        str_replace:
          template: '%stackname%-bastion'
          params:
            '%stackname%': { get_param: deployment_name }
      PrivateNet: { get_param: private_net }
      PrivateSubnet: { get_param: private_subnet }
      PublicNet: { get_param: public_net }
      SaltmasterIP: { get_param: SaltmasterIP }
      private_key: { get_param: private_key }
      pnda_secgroup: { get_param: PndaSecGroup }
      cluster_name: { get_param: deployment_name }
      pnda_flavor: { get_param: PndaFlavor }

  kafka:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: OS::Pnda::kafka
        properties:
          Flavor: { get_param: KafkaFlavor }
          Image: { get_param: image_id }
          KeyName: { get_param: KeyName }
          name:
            str_replace:
              template: '%stackname%-kafka-%index%'
              params:
                '%stackname%': { get_param: deployment_name }
          NodeIndex: '%index%'
          PrivateNet: { get_param: private_net }
          PrivateSubnet: { get_param: private_subnet }
          SaltmasterIP: { get_param: SaltmasterIP }
          sec_group: { get_resource: KafkaSecGroup }
          cluster_name: { get_param: deployment_name }
          pnda_secgroup: { get_param: PndaSecGroup }
          pnda_flavor: { get_param: PndaFlavor }

  manager1:
    type: OS::Pnda::manager1
    properties:
      Flavor: { get_param: Manager1Flavor }
      Image: { get_param: image_id }
      KeyName: { get_param: KeyName }
      name:
        str_replace:
          template: '%stackname%-cdh-mgr1'
          params:
            '%stackname%': { get_param: deployment_name }
      PrivateNet: { get_param: private_net }
      PrivateSubnet: { get_param: private_subnet }
      SaltmasterIP: { get_param: SaltmasterIP }
      pnda_secgroup: { get_param: PndaSecGroup }
      cluster_name: { get_param: deployment_name }
      pnda_flavor: { get_param: PndaFlavor }
  edge:
    type: OS::Pnda::edge
    properties:
      Flavor: { get_param: EdgeFlavor }
      Image: { get_param: image_id }
      KeyName: { get_param: KeyName }
      name:
        str_replace:
          template: '%stackname%-cdh-edge'
          params:
            '%stackname%': { get_param: deployment_name }
      PrivateNet: { get_param: private_net }
      PrivateSubnet: { get_param: private_subnet }
      SaltmasterIP: { get_param: SaltmasterIP }
      cluster_name: { get_param: deployment_name }
      pnda_secgroup: { get_param: PndaSecGroup }
      pnda_flavor: { get_param: PndaFlavor }
  dn:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: DataNodes }
      resource_def:
        type: OS::Pnda::dn
        properties:
          Flavor: { get_param: DatanodeFlavor }
          Image: { get_param: image_id }
          KeyName: { get_param: KeyName }
          name:
            str_replace:
              template: '%stackname%-cdh-dn-%index%'
              params:
                '%stackname%': { get_param: deployment_name }
          NodeIndex: '%index%'
          PrivateNet: { get_param: private_net }
          PrivateSubnet: { get_param: private_subnet }
          SaltmasterIP: { get_param: SaltmasterIP }
          sec_group: { get_resource: DNSecGroup }
          volume_size: { get_param: DatanodeVolumeSize }
          mountpoint: { get_param: DatanodeMountpoint }
          cluster_name: { get_param: deployment_name }
          pnda_secgroup: { get_param: PndaSecGroup }
          pnda_flavor: { get_param: PndaFlavor }

outputs:
  kafka_hosts:
    value: { get_attr: [kafka, hosts_entry] }
